apiVersion: v1
kind: Service
metadata:
  name: hello-k8s-svc
spec:
  type: NodePort   # minikube라 NodePort가 간단합니다
  selector:
    app: hello-k8s
  ports:
    - port: 80
      targetPort: 8180
      nodePort: 30080   # 비워두면 자동 배정; 고정 원하시면 이 번호 유지(가능한 범위 30000-32767)
